# Generated by Django 6.0.6 on 2026-07-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(db_column='variable', max_length=50)),
                ('value', models.FloatField(db_column='valor')),
                ('risk', models.CharField(db_column='riesgo', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='fecha', db_index=True)),
                ('building', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='buildings.building')),
            ],
            options={
                'db_table': 'lectura_sensor',
                'indexes': [models.Index(fields=['building', 'variable', 'timestamp'], name='lectura_sen_id_edif_d0ba34_idx')],
            },
        ),
    ]
