# Generated by Django 6.0.6 on 2026-07-14 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(db_column='fecha', db_index=True, default=django.utils.timezone.now),
        ),
    ]
