# Generated by Django 6.0.6 on 2026-07-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50)),
                ('max_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
            options={
                'verbose_name': 'Límite de Sensor',
                'verbose_name_plural': 'Límites de Sensores',
                'db_table': 'limite_sensor_config',
                'unique_together': {('building', 'variable')},
            },
        ),
    ]
