# Generated by Django 6.0.6 on 2026-06-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=50)),
                ('direction', models.CharField(default='higher', max_length=10)),
                ('low', models.FloatField()),
                ('medium', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Configuración de Umbral',
                'verbose_name_plural': 'Configuraciones de Umbrales',
                'db_table': 'umbral_config',
                'unique_together': {('building', 'variable')},
            },
        ),
    ]
