# Generated by Django 6.0.6 on 2026-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresholds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdconfig',
            name='crit_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='crit_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
