# Generated by Django 6.0.6 on 2026-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thresholds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
