# Generated by Django 6.0.6 on 2026-06-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=16, unique=True)),
                ('first_name', models.CharField(db_column='primer_nombre', max_length=40)),
                ('middle_name', models.CharField(blank=True, db_column='segundo_nombre', default='', max_length=40)),
                ('first_last_name', models.CharField(db_column='primer_apellido', max_length=40)),
                ('second_last_name', models.CharField(blank=True, db_column='segundo_apellido', default='', max_length=40)),
                ('email', models.EmailField(max_length=75, unique=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('US', 'Usuario'), ('SA', 'Super Administrador')], default='US', max_length=2)),
                ('registered', models.BooleanField(db_column='registrado', default=False)),
                ('alerts_disabled', models.BooleanField(default=False)),
                ('alerts_disabled_until', models.DateTimeField(blank=True, null=True)),
                ('alerts_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
