# Generated by Django 6.0.6 on 2026-07-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='alerts_disabled',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='alerts_disabled_until',
        ),
    ]
