# Generated by Django 6.0.6 on 2026-07-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_alerts_cleared_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='history_cleared_at',
        ),
    ]
