# Generated by Django 6.0.6 on 2026-06-30 21:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(db_column='id_edificio', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nb_edificio', max_length=40)),
                ('rif', models.CharField(max_length=16, unique=True)),
                ('address', models.CharField(db_column='direccion', max_length=100)),
                ('floors', models.PositiveIntegerField(db_column='cantidad_pisos', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'edificio',
            },
        ),
        migrations.CreateModel(
            name='MonitoringEquipment',
            fields=[
                ('id', models.AutoField(db_column='id_equipo_monitoreo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nb_equipo', max_length=255)),
                ('equipment_type', models.CharField(choices=[('bomba', 'Bomba de agua'), ('elevador', 'Elevador')], db_column='tipo', default='bomba', max_length=20)),
                ('status', models.CharField(choices=[('operativo', 'Operativo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='operativo', max_length=20)),
                ('building', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='buildings.building')),
            ],
            options={
                'db_table': 'equipo_monitoreo',
                'ordering': ['equipment_type'],
                'constraints': [models.UniqueConstraint(fields=('building', 'equipment_type'), name='uq_building_equipment_type')],
            },
        ),
        migrations.CreateModel(
            name='UserBuilding',
            fields=[
                ('id', models.AutoField(db_column='id_asignacion', primary_key=True, serialize=False)),
                ('building', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='buildings.building')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='building_assignments', to='users.usuario')),
            ],
            options={
                'db_table': 'usuario_edificio',
                'constraints': [models.UniqueConstraint(fields=('user', 'building'), name='uq_usuario_edificio')],
            },
        ),
    ]
