# Generated by Django 6.0.6 on 2026-07-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='fecha', db_index=True)),
                ('message', models.JSONField(blank=True, db_column='mensaje', default=dict)),
                ('resolved', models.BooleanField(db_column='resuelto', default=False)),
                ('fault_type', models.CharField(blank=True, db_column='tipo_falla', max_length=50, null=True)),
                ('affected_variables', models.JSONField(blank=True, db_column='variables_afectadas', default=list)),
                ('monitoring_equipment', models.ForeignKey(blank=True, db_column='id_equipo_monitoreo', null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.monitoringequipment')),
                ('user', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
    ]
