# Generated by Django 6.0.6 on 2026-07-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='resolved',
            field=models.BooleanField(db_column='resuelto', default=False),
        ),
    ]
