# Generated by Django 6.0.6 on 2026-07-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDismissedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, db_column='descartado_en')),
                ('history_record', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, to='history.history')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'historial_descartado',
                'constraints': [models.UniqueConstraint(fields=('user', 'history_record'), name='uq_user_history_dismissed')],
            },
        ),
    ]
