# Generated by Django 6.0.6 on 2026-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='affected_variables',
            field=models.JSONField(blank=True, db_column='variables_afectadas', default=list),
        ),
        migrations.AddField(
            model_name='history',
            name='fault_type',
            field=models.CharField(blank=True, db_column='tipo_falla', max_length=50, null=True),
        ),
    ]
